### ISSUE TITLE
Each star reactions will add the message to the starboard.

### ISSUE THREAD

**Issue by Nefomemes** [vierofernando/username601#3]
__How to reproduce:__
-Have starboard enabled.
-Star your message. Then have other star it.

__Expected result:__
-The message should be sent once to the starboard. 

__Actual result:__
-The message got sent to the starboard twice and even more.

__Server information:__
Star requirement: 1
Server: The bot's support server

__Other information:__
I have informed the bot owner of this issue, and the bot owner have already be aware of this issue.

__**Fixed:**__
The bot owner have released an update that fixed this issue. Awaiting issue to be closed.

![Screenshot_20200904-115648_Discord.jpg](https://user-images.githubusercontent.com/66000635/92201103-d5129200-eea5-11ea-9b82-06f3a53ccc18.jpg)

__Attachments:__
![Screenshot_20200904-114613_Discord.jpg](https://user-images.githubusercontent.com/66000635/92200554-6c76e580-eea4-11ea-89bb-ff6e45cd51fb.jpg)

**Comment by Nefomemes** [comment]
Bruh, I forgot I can close this issue by myself.

# Fine, I will do it my self.

**Comment by vierofernando** [comment]
this issue has been fixed dummie

**Comment by Nefomemes** [comment]
> this issue has been fixed dummie

Bruh, I sent this before the update. So I close it immediately, duh.
