### ISSUE TITLE
guessavatar game

### ISSUE THREAD

**Issue by digasred** [vierofernando/username601#7]
it doesn work when i try to run it it says raise IndexError('Cannot choose from an empty sequence')
IndexError: Cannot choose from an empty sequence and r = getrandbits(k)          # 0 <= r < 2**k
ValueError: number of bits must be greater than zero

**Comment by vierofernando** [comment]
hmm did you copied the code straight from the repo? or maybe you ran it on a server with small members, because i tried it on my bot and it works perfectly.

**Comment by digasred** [comment]
i copied the code straight from the repo and I have my bot in two servers, one its not so full, and one has like 50 people and the code still doesn't work

**Comment by vierofernando** [comment]
Please do not copy straight from the repo because there may be some bugs
